### ISSUE TITLE
Next Gruntjs.com

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/gruntjs.com#128]
Tracking issue for the updated version of the site.

Documentation ( https://github.com/gruntjs/grunt-docs )
- [ ] Update documentation to markdown with set layouts. Should either use docpad or something like this: 
https://medium.com/code-stories/building-markdown-based-developer-docs-87c0317c56f7
- [ ] Branch docs based on version number
- [ ] Add a dropdown to select the version of Grunt you want to use ( i.e https://docs.angularjs.org/api )
- [ ] Archive 0.3 docs, remove from main docs

Plugins
- [ ] Minor fixes to design
- [ ] Minor fixes to handle multiple versions of Grunt  

Other
- [x] Update to Express 4
- [ ] Ship logo/branding guidelines 
- [ ] Check out `heroku-repo` addon for site rebuilt on Heroku

**Comment by GeorgeWL** [comment]
Looked at Hexo.io as an option?
