### ISSUE TITLE
Gruntfile builder mini-app

### ISSUE THREAD

**Issue by leobalter** [gruntjs/gruntjs.com#142]
That's a @cowboy suggestion to create a page to help developers build a sample Gruntfile.

The objective is to help new developers create and understand how to build the file, handpicking the desired tasks and setting their options.

It still needs some briefing and everything else.

**Comment by JKAussieSkater** [comment]
[gruntfile-gen](https://github.com/bodyflex/gruntfile-gen) is very impressive!

I think it would be great tool to use with the Grunt Docs . . . However it isn't licensed, so we'd have to get permission if we wanted to do that.  I've made an [issue request](https://github.com/bodyflex/gruntfile-gen/issues/3) for a license.

Anyway, this is an old thread, but should we still revisit this after 1.0?

**Comment by vladikoff** [comment]
Not planning to do this as part of main project at this time.
