### ISSUE TITLE
Site appears to be down.

### ISSUE THREAD

**Issue by cowboy** [gruntjs/gruntjs.com#158]
@vladikoff any idea what might be going on?

**Comment by tkellen** [comment]
grunt.herokuapp.com is up, looks like gruntjs.com points to a different IP right now?

**Comment by cowboy** [comment]
I changed the DNS, but the TTL is 1800 so it might take a bit.

**Comment by cowboy** [comment]
I changed the TTL to 300 so future IP changes will propagate more quickly.

**Comment by cowboy** [comment]
Back up!
