### ISSUE TITLE
Missing plugin on search

### ISSUE THREAD

**Issue by pracucci** [gruntjs/gruntjs.com#164]
I'm the author of https://www.npmjs.com/package/grunt-aws-apigateway - when I search "apigateway" on gruntjs.com plugins I can't find this package. I'm pretty sure the error is on my side, but I can't figure it out. Any hint?

**Comment by XhmikosR** [comment]
@vladikoff: can this be due to not updated plugins.json?

**Comment by vladikoff** [comment]
this was fixed :+1:
