### ISSUE TITLE
Update "built with GRUNT" badge documentation

### ISSUE THREAD

**Issue by andersevenrud** [gruntjs/gruntjs.com#165]
From https://github.com/gruntjs/grunt/issues/1365

> Could you make an alternate badge without borders and white text shadow ?
> It looks a lot better imo and fits a lot better when having multiple badges.

This was my attempt at it:

Preview: ![Badge PNG export example](https://www.dropbox.com/s/0hptdw8n8jfzc3k/grunt-badge-112x20.png?dl=1)

SVG: https://www.dropbox.com/s/fy1vljhtetkiuub/grunt-badge.svg?dl=0

PR: https://github.com/gruntjs/gruntjs.com/pull/163

**Comment by JKAussieSkater** [comment]
Based on the consensus in [the discussion](https://github.com/gruntjs/grunt/issues/1365), I believe there was a communal agreement to use the one you're providing. :+1: 
It does look really good!

I'm a bit confused as to why this is a ticketed issue . . .
What is this issue requesting, that the pull request isn't already requesting?
Or more simply, what is the issue?

**Comment by andersevenrud** [comment]
@JKAussieSkater I was directed here in gruntjs/grunt#1365

There is no issue, i simply "transfered" it here because I was told to do so :)

**Comment by JKAussieSkater** [comment]
Merged!

I'll repurpose this ticket as a reminder to update the documentation.

As per [this discussion](https://github.com/gruntjs/gruntjs.com/pull/163#issuecomment-180033541) the existing PNG version will deprecated and superseded by your SVG version.

**Comment by andersevenrud** [comment]
Nice :+1: Thanks!

**Comment by andersevenrud** [comment]
@JKAussieSkater Could you let me know when it is available so I can update my README ? :)

**Comment by JKAussieSkater** [comment]
Sure! Once it's publicly available on the website, I'll let you know 😀

**Comment by vladikoff** [comment]
@JKAussieSkater https://cdn.gruntjs.com/builtwith.svg is LIVE :+1:

**Comment by JKAussieSkater** [comment]
WOOHOO!!!

@andersevenrud, closing this issue now :+1:

**Comment by JKAussieSkater** [comment]
Just remembered, need to update the docs first!

**Comment by andersevenrud** [comment]
Sweet :D
