### ISSUE TITLE
The font is hard to read

### ISSUE THREAD

**Issue by craftpip** [gruntjs/gruntjs.com#200]
i noticed on chrome that the p tags text are really light
font-weight: 200, which is really hard to read.

This is how it looks
http://pasteboard.co/Pjj12h0FS.png

Please consider increasing the font-weight to 400.
Thanks 👍

**Comment by XhmikosR** [comment]
I'll have a look in the next days. Weird that with FF I can't reproduce the issue.

**Comment by craftpip** [comment]
Yeah this is just with chrome.

**Comment by XhmikosR** [comment]
The problem is OS dependent. It's because of the font Bootstrap 2.x is using and your OS.

I switched to the system font stack and should be OK now.
