### ISSUE TITLE
Is gruntjs.com using Heroku? Because I just got this email from them:

### ISSUE THREAD

**Issue by cowboy** [gruntjs/gruntjs.com#205]
The Heroku Cedar-14 stack was previously deprecated on May 3, 2018, and the end-of-life (EOL) window has now begun in accordance with Heroku's stack policy. Your Heroku account has one or more apps running on the Cedar-14 stack.

Your apps running on the Cedar-14 stack will continue to run and build. We will continue to apply critical security updates to the Cedar-14 stack.

We are providing you a grace period of 1 year during which your apps on Cedar-14 will still run, build, and receive critical security updates. However, you should upgrade your apps to the latest stack, which is currently Heroku-18.

Key dates:

    May 3, 2018: Heroku announces deprecation of Cedar-14 for April 2019.
    May 1, 2019: EOL window for Cedar-14 begins. Apps on Cedar-14 will continue to run, build, and receive security updates. Apps and builds running on later stacks will not be affected.
    May 1, 2020: EOL window for Cedar-14 ends. Apps on Cedar-14 will continue to run, but will no longer build or receive security updates. Apps running on later stacks will not be affected.

What do I need to do?
Please use this Dev Center guide to upgrade your apps on Cedar-14 to the latest stack.

What apps do I have on the Cedar-14 stack?
Your account has the following apps running on Cedar-14:
grunt

Note this may be a partial list, please see below to get a definitive list of Cedar-14 apps via the Heroku CLI:

$ heroku plugins:install apps-table
$ heroku apps:table --filter="STACK=cedar-14"

Or to show apps by team:

$ heroku apps:table --team=my-team --filter="STACK=cedar-14"

Will my Cedar-14 apps continue to run?
Yes, your existing apps on Cedar-14 will continue to run, but once we disable builds, you won't be able to deploy new versions until you upgrade your apps to the latest stack.

Why has the Cedar-14 end-of-life window begun?
The Ubuntu 14.04 operating system, released in 2014, serves as the base for the Cedar-14 stack. Heroku's operating system stacks are based on the “Long Term Support” Ubuntu releases provided by Canonical. The standard Ubuntu LTS lifecycle is 4 years, so this 14.04 EOL is an expected event per our stack policy.

What is a stack?
A stack is an operating system image that is curated and maintained by Heroku. Stacks are typically based on an existing open-source Linux distribution, such as Ubuntu. Heroku applications target a specific stack, and buildpacks are responsible for transforming an app’s source code into an executable package that is compatible with that stack.

I have additional questions about the Cedar-14 EOL.
Additional information is available in the Cedar-14 End-of-Life FAQ. Our support team will update this FAQ with additional resources over time.

Happy Coding,
Heroku

**Comment by cowboy** [comment]
LMK if I need to do anything!

**Comment by vladikoff** [comment]
Ok! I shall take a look at this!

**Comment by vladikoff** [comment]
This is fine for now
