### ISSUE TITLE
Headings/anchor style on Documentation are broken

### ISSUE THREAD

**Issue by pedrosanta** [gruntjs/gruntjs.com#206]
Hello,

I've noticed that on the [Grunt Documentation](https://gruntjs.com/getting-started) the style of the headings/anchors is broken, and I think I know why, but not sure why it's wrong on live site. (Possibly outdated? Different dependency versions?)

This is how it looks on the live site:

<img width="1792" alt="Screenshot 2019-10-01 at 10 51 39" src="https://user-images.githubusercontent.com/2737/65952227-78a72700-e439-11e9-9d3c-fe883edda2cf.png">

But, when I clone this repo and build it locally the headings/anchors are correct:

<img width="1792" alt="Screenshot 2019-10-01 at 10 53 08" src="https://user-images.githubusercontent.com/2737/65952355-ae4c1000-e439-11e9-8757-9dc667723936.png">

**Now**, if you look closely between these two, _on the live site the heading text is placed inside the `<a>` tag_, which by per `.anchor` class style has a `font-family: icomoon!important;`, hence the wrong serif font style on live site.

```html
<h2>
  <a class="anchor" href="#installing-the-cli" name="installing-the-cli">
    Installing the CLI
  </a>
</h2>
```

**But** on my local repo, _the heading text is placed outside the `<a>` tag_, which makes it pick up the correct styling, with **Lato** font.

```html
<h2>
  <a class="anchor" href="#installing-the-cli" id="installing-the-cli"></a>
  Installing the CLI
</h2>
```

I've already peeked into the code and history to confirm if the deployed version on live site is outdated, or if there could be differences between the versions of the `marked` dependency used, etc, but to no avail.

Could any of the maintainers take a look to this?

**Comment by pedrosanta** [comment]
@XhmikosR any thoughts/comment on this?

**Comment by XhmikosR** [comment]
@vladikoff please release a new tag to see if it fixes the issue

**Comment by XhmikosR** [comment]
BTW it works fine for me here. Could either be a caching issue or a Cloudflare issue and someone needs to purge the cache there.

**Comment by pedrosanta** [comment]
Just throwing the bump here that this is still happening... 😅

**Comment by pedrosanta** [comment]
@XhmikosR @vladikoff any ideas/comments on this one? 🙂

**Comment by XhmikosR** [comment]
I'm unsure how to proceed with this, sorry.

**Comment by pedrosanta** [comment]
Ok @XhmikosR , like, I appreciate your honesty. 😄 Fair game—I'm also a bit confused by it. I have a sense that might be some dependency discrepancy, but not sure.

Was it interesting to like, share the `package-lock.json` of the live site environment, to see if we could replicate the issue on a local setting?

**Comment by pedrosanta** [comment]
Hey @XhmikosR looks like this issue is fixed now on https://gruntjs.com/getting-started.

Pack up bois, our work here is done. 🍻

**Comment by vladikoff** [comment]
woo we did it!
