### ISSUE TITLE
The plugins page shows no plugins

### ISSUE THREAD

**Issue by karl-sjogren** [gruntjs/gruntjs.com#207]
The plugins page shows no plugins right now. The source file which it downloads, https://gruntjs.com/plugin-list.json, is just an object with an empty JSON array.

**Comment by westurner** [comment]
Can confirm

**Comment by vladikoff** [comment]
yea the api we used to fetch the download list disappeared. I am trying to find a new one that we can use to fetch the list

**Comment by vladikoff** [comment]
plugins are back at https://gruntjs.com/plugins
