### ISSUE TITLE
https://gruntjs.com/plugins returns "undefined" as href value

### ISSUE THREAD

**Issue by lynxSven** [gruntjs/gruntjs.com#213]
The <a> Tag which leads to a plugin on the subside https://gruntjs.com/plugins has the href value "undefined" for every list element.

e.g.
```
<tr role="row" class="odd">
    <td><a class="plugin contrib" href="undefined"><span class="name-description"><span
                    class="title">grunt-contrib-cssmin</span><span class="author">by Grunt Team</span><span
                    class="desc">Minify CSS</span></span></a></td>
    <td><span class="score">34</span></td>
</tr>
```

What am I using:
Windows 10
Firefox 68.6.0esr (64-Bit)
Firefox addons NoScript (which doesn't block any scripts)

**Comment by vladikoff** [comment]
oh weird, i thought i deployed a fix for that. let me check again..

**Comment by vladikoff** [comment]
should be fixed now!
