### ISSUE TITLE
Black Lives Matter solidarity statement

### ISSUE THREAD

**Issue by isaacdurazo** [gruntjs/gruntjs.com#218]
Hi @vladikoff, I've been helping to add Black Lives Matter solidarity statements to some project's websites (like [Test262 Report](https://test262.report) and [P5.js](https://p5js.org/)) and would love to do the same for Grunt. Perhaps something similar to what [emberjs.com](https://emberjs.com/) has implemented in its website. What do you think?

If this is ok with you I can take care if submitting a PR with the changes.

**Comment by vladikoff** [comment]
@isaacdurazo Sure! Send a PR in for that! Let me know if you need any help

**Comment by vladikoff** [comment]
This was deployed
