### ISSUE TITLE
Built with Grunt badge broken

### ISSUE THREAD

**Issue by tecfu** [gruntjs/gruntjs.com#226]
See: https://gruntjs.com/built-with-grunt-badge

Possibly same issue as https://github.com/gruntjs/grunt-docs/issues/91 ?

**Comment by Krinkle** [comment]
The original URL at <https://cdn.gruntjs.com/builtwith.svg> now also works again. Either URL is fine to use.

Server configuration resides at https://github.com/jquery/infrastructure-puppet, where we now include cdn.gruntjs.com in the Let's Encrypt certificate.
