### ISSUE TITLE
hi ,I just found an issue to commit

### ISSUE THREAD

**Issue by FairyRoc** [gruntjs/gruntjs.com#227]
url: http://www.gruntjs.net/configuring-tasks
issue:   I found sth wrong with  the following description 

> "下面以concat任务配置为例，运行grunt concat:sample时将通过banner中的/\* abcde _/连同foo/_.js+bar/_.js+bar/_.js匹配的所有文件来生成一个名为build/abcde.js的文件。" 

one of the `bar/_.js` should be `baz/_.js`.

**Comment by Krinkle** [comment]
This bug does not exist in the original English text at https://gruntjs.com/configuring-tasks#templates.

It appears to be a bug in the translation. I don't know where the gruntjs.net source is, but you may have to contact them instead.

See also https://github.com/gruntjs/gruntjs.com/issues/203. https://grunt.docschina.org/docs/configuring-tasks.html appears to contain the same mistake.
