### ISSUE TITLE
Create a proper "Documentation" index page

### ISSUE THREAD

**Issue by JKVeganAbroad** [gruntjs/gruntjs.com#228]
Currently the "Documentation" link on Grunt's [website header](https://github.com/gruntjs/gruntjs.com/blob/master/src/tmpl/blocks/header.jade) links to the same location as "Getting Started".

It would be more practical to instead have the documentation link to a "documentation overview" landing page. Also, removing duplicated URLs is a good idea.

Feel free to comment to this issue if you have ideas on what a "Documentation Overview" landing page should look like.

**Comment by Krinkle** [comment]
It looks like the page is working fine at https://gruntjs.com/documentation, so I'll update the nav to point to it.
