### ISSUE TITLE
Note what version new features were introduced in.

### ISSUE THREAD

**Issue by cowboy** [gruntjs/gruntjs.com#233]
For example, the `extDot` option for file globbing was added in `0.4.3` but the docs don't state this. Someone using an older version of Grunt might be confused as to why it's not working. Would it be possible to, both retroactively and in the future, add something like the following to new methods, options and method signatures?

SO AND SO DESCRIPTION OF THING. _[Added in x.y.z]_

Eg.
- `ext` Replace any existing extension with this value in generated `dest` paths.
- `extDot` Used to indicate where the period indicating the extension is located. Can take either `'first'` (extension begins after the first period in the file name) or `'last'` (extension begins after the last period), and is set by default to `'first'`. _[Added in 0.4.3]_
- `flatten` Remove all path parts from generated `dest` paths.

**Comment by Krinkle** [comment]
Looks like we've got "Added in" on 4 pages now.

https://github.com/search?q=repo%3Agruntjs%2Fgrunt-docs%20%22Added%20in%22&type=code

If there's more missing, we can always add more. I'll close this as resolved.
