### ISSUE TITLE
Logo usage -  do's and dont's section

### ISSUE THREAD

**Issue by isaacdurazo** [gruntjs/gruntjs.com#44]
This will be a section with a brand guide for Grunt and a place were people can download a zip file with different formats of the logo.

Here are 2 good references: https://twitter.com/logo and http://www.w3.org/html/logo/

**Comment by DougReynolds** [comment]
Hello, I am writing a getting started with Grunt book which will be published with Packt publishing near the end of this year. I would like to request permission to use the Grunt logo. The example documentation provided in this issue point to twitter and github terms of use and specify requiring permission.  Please advise.

**Comment by JKAussieSkater** [comment]
Lets continue this conversation on the [grunt-docs](https://github.com/gruntjs/grunt-docs/issues/100).
