### ISSUE TITLE
Home page shows the project title as "dorkq" on some Android devices

### ISSUE THREAD

**Issue by drfloob** [gruntjs/gruntjs.com#81]
See here:
http://www.browserstack.com/screenshots/2308d26f99f0b5915b53829c4ae5f9567b2d84be

I haven't tried to figure out why. @practicum noticed that the letters are all 3 off and lowercase. G-3=d, R-3=o ...

**Comment by Pomax** [comment]
I'd seriously still like to know what happened here, because I know my OpenType, and unless the font somehow has GSUB rules specific to running a Caesar cypher, that is not a thing that will spontaneously happen.

**Comment by davelab6** [comment]
There was a bug in Java where fonts were cached in way that used Glyph IDs, so when a font was updated and the GID order changed, you'd see a caesar cypher effect. Its possible there is such a bug in Android.

**Comment by Pomax** [comment]
That's quite the bug. Would you happen to know the bug link for that on the java side?

**Comment by davelab6** [comment]
https://bugs.openjdk.java.net/browse/JDK-8051892

https://bugs.openjdk.java.net/browse/JDK-7184798

**Comment by ashrocket** [comment]
Tee spring is a YC company that does exactly this.  https://teespring.com

**Comment by itaditya** [comment]
Grunt at web dev 🤣
