### ISSUE TITLE
clean up -webkit- css

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/gruntjs.com#84]
clean up -webkit- css
Linked from https://github.com/gruntjs/gruntjs.com/issues/27

**Comment by verpixelt** [comment]
@vladikoff I'd like to take care of it. Is it just removing -webkit- or do you wanna get rid of all the prefixes (taking care of it with an automated process)?

**Comment by vladikoff** [comment]
We will probably work on a new design / site so do not worry about this one. Thanks for asking though!

**Comment by verpixelt** [comment]
k, thanks for getting back so quickly. I'd be happy to help in that process, if you need someone.
